package id.holigo.services.common.model;

public enum OrderStatusEnum {
    PROCESS_BOOK, BOOKED, BOOK_FAILED, PROCESS_ISSUED, WAITING_ISSUED, ISSUED, RETRYING_ISSUED, ISSUED_FAILED,
    ORDER_EXPIRED, ORDER_CANCELED
}
